name: GitHub Actions Demo
on:
  push:
    branches: 
    - main
    paths-ignore: "./.github/**"
  pull_request:
    branches:
    - main
  schedule:
    - cron: "15 6 * * SUN"
  workflow_dispatch:
    
jobs:
  Build:
    name: "Build Job"
    runs-on: "ubuntu-latest"
    steps:
    - name: Test
      run: echo ${{github.event_name}}
