name: Reusable Workflow
on: 
  workflow_call:
    inputs:
      who-to-greet:
        type: string
        required: true
        default: "Hello World"
    outputs:
      current-time:
        description: 'The time when greeting.'
        value: ${{ jobs.reusable-job.outputs.current-time }}
jobs:
  reusable-job:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello ${{ inputs.who-to-greet }}"
    - run: echo "time=$(date)" >> $GITHUB_OUTPUT
